### ISSUE TITLE
'String' is a special class name

### ISSUE THREAD

**Issue by NiklasRiewald** [NumPHP/NumPHP#11]
NumArray throws a fatal error under PHP 7:

> PHP Fatal error:  Cannot use NumPHP\Core\NumArray\String as String because 'String' is a special class name in C:\Users\Nick\PhpstormProjects\PhLe\vendor\numphp\numphp\src\NumPHP\Core\NumArray.php on line 21 

So you should rename your String class :)

**Comment by GordonLesti** [comment]
Hello @NiklasRiewald 
thank you for the hint. I hope this is fixed with version [1.1.0](https://github.com/NumPHP/NumPHP/tree/1.1.0).

**Comment by NiklasRiewald** [comment]
nice, thanks for the quick fix
