### ISSUE TITLE
manual installation does not work

### ISSUE THREAD

**Issue by ckun789** [NumPHP/NumPHP#15]
I am trying to follow the manual installation guideline saying "Download the latest package, extract it and include the file vendor/autoload.php in your project.". But there is not such file autoload.php. Can you please assist me in setting this up. Cheers. Chris

**Comment by GordonLesti** [comment]
Hello @ckun789 
just download [numphp-1.1.0.tar.gz](https://github.com/NumPHP/NumPHP/releases/download/1.1.0/numphp-1.1.0.tar.gz) and extract it. The `autoload.php` file is in the directory `numphp-1.1.0/numphp/vendor`. I hope this helps you.

Best Regards
Gordon
